services:
  db:
    image: postgis/postgis:latest
    container_name: iservice_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_DOCKER:-5433}:5432"
    volumes:
      - iservice_db_data:/var/lib/postgresql/data

volumes:
  iservice_db_data: